var command_dict = {
    "join": join,
    "leave": leave,
    "stats csgo": stats_csgo,
    "stats r6s": stats_r6s,
    "play": music_play,
    "stop": music_stop,
    "start": music_start,
    "queue": music_queue,
    "skip": music_,
    "alarm": alarm,
    "timer": timer,
    "weather": weather,
    "weather city": weather_city,
    "help": help,
    "einar": einar,
    "tts": tts,
}

var command_list = (
    "join",
    "leave",
    "stats csgo",
    "stats r6s",
    "play",
    "stop",
    "start",
    "queue",
    "skip",
    "alarm",
    "timer",
    "wether",
    "weather city",
    "help",
    "einar",
    "tts",
)
  